server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: product_route  # 当前路由的标识, 要求唯一
          uri: lb://service-product # 请求要转发到的地址
          predicates: # 断言(就是路由转发要满足的条件)
            # 匹配路径转发
            - Path=/product-serv/** # 当请求路径满足Path指定的规则时,才进行路由转发
            - Before=2022-02-18T00:00:00.000+08:00 #限制请求时间在2022-02-18之前 \- Method=POST #限制请求方式为POST
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
